<a href="https://colab.research.google.com/github/JesusSJuarez/AlgebraLineal/blob/main/Examen_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Librerias

In [1]:
!pip install --target=$nb_path nacal
from nacal import *

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.0/40.0 kB 1.1 MB/s eta 0:00:00


##Ejercicio 1

1. Para la siguiente matriz $$\left[ \begin{array}{cccc}3&-2&2&1\\1&-1&-1&-3\\2&1&2&4\\4&-4&1&2\\ \end{array} \right]$$ lleva a cabo el algoritmo de eliminación paso a paso.

Escribe en una celda separada cada operacion elemental.

In [53]:
w=Vector((3,1,2,4)); x=Vector((-2,-1,1,-4)); y= Vector((2,-1,2,1)); z= Vector((1,-3,4,2))
M= Matrix([w,x,y,z])
M

$\left[ \begin{array}{cccc}3&-2&2&1\\1&-1&-1&-3\\2&1&2&4\\4&-4&1&2\\ \end{array} \right]$

In [54]:
M&T((3,2))

$\left[ \begin{array}{cccc}3&-6&2&1\\1&-3&-1&-3\\2&3&2&4\\4&-12&1&2\\ \end{array} \right]$

In [55]:
M&T((2,1,2))

$\left[ \begin{array}{cccc}3&0&2&1\\1&-1&-1&-3\\2&7&2&4\\4&-4&1&2\\ \end{array} \right]$

In [56]:
M&T((3,3))

$\left[ \begin{array}{cccc}3&0&6&1\\1&-1&-3&-3\\2&7&6&4\\4&-4&3&2\\ \end{array} \right]$

In [57]:
M&T((-2,1,3))

$\left[ \begin{array}{cccc}3&0&0&1\\1&-1&-5&-3\\2&7&2&4\\4&-4&-5&2\\ \end{array} \right]$

In [58]:
M&T((3,4))

$\left[ \begin{array}{cccc}3&0&0&3\\1&-1&-5&-9\\2&7&2&12\\4&-4&-5&6\\ \end{array} \right]$

In [59]:
M&T((-1,1,4))

$\left[ \begin{array}{cccc}3&0&0&0\\1&-1&-5&-10\\2&7&2&10\\4&-4&-5&2\\ \end{array} \right]$

In [60]:
M&T((-5,2,3))

$\left[ \begin{array}{cccc}3&0&0&0\\1&-1&0&-10\\2&7&-33&10\\4&-4&15&2\\ \end{array} \right]$

In [61]:
M&T((-10,2,4))

$\left[ \begin{array}{cccc}3&0&0&0\\1&-1&0&0\\2&7&-33&-60\\4&-4&15&42\\ \end{array} \right]$

In [62]:
M&T((11,4))

$\left[ \begin{array}{cccc}3&0&0&0\\1&-1&0&0\\2&7&-33&-660\\4&-4&15&462\\ \end{array} \right]$

In [63]:
M&T((-20,3,4))

$\left[ \begin{array}{cccc}3&0&0&0\\1&-1&0&0\\2&7&-33&0\\4&-4&15&162\\ \end{array} \right]$

##Ejercicio 2

2. Escriba las siguientes matrices elementales de orden 4.

(a) I τ
[(−7)1+3]

In [64]:
I(4) & T( (-7,1,3) )

$\left[ \begin{array}{cccc}1&0&-7&0\\0&1&0&0\\0&0&1&0\\0&0&0&1\\ \end{array} \right]$

(b) I τ
[(1)1+4]

In [65]:
I(4) & T( (1,1,4) )

$\left[ \begin{array}{cccc}1&0&0&1\\0&1&0&0\\0&0&1&0\\0&0&0&1\\ \end{array} \right]$

(c) I τ
[(3)2+1]

In [66]:
I(4) & T( (3,2,1) )

$\left[ \begin{array}{cccc}1&0&0&0\\3&1&0&0\\0&0&1&0\\0&0&0&1\\ \end{array} \right]$

(d) I τ
[(−10)3]

In [67]:
I(4) & T( (-10,3) )

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&0&-10&0\\0&0&0&1\\ \end{array} \right]$

##Ejercicio 3

3. Sea la matriz A = $\left[ \begin{array}{cccc}1&1&1&1\\0&1&1&1\\1&2&3&4\\4&-4&1&2\\ \end{array} \right]$
, exprese las siguientes transformaciones elementales de

A como productos de A por matrices elementales y escriba el resultado:

(a) Multiplicar la primera columna por 3. (b) Restar la primera columna de la segunda.

In [68]:
w= Vector((1,0,1,4)); x=Vector((1,1,2,-4)); y= Vector((1,1,3,1)); z= Vector((1,1,4,2))
A= Matrix([w,x,y,z])
A

$\left[ \begin{array}{cccc}1&1&1&1\\0&1&1&1\\1&2&3&4\\4&-4&1&2\\ \end{array} \right]$

In [69]:
A=A * ( I(A.n) &  T((3,1)) )
A

$\left[ \begin{array}{cccc}3&1&1&1\\0&1&1&1\\3&2&3&4\\12&-4&1&2\\ \end{array} \right]$

In [70]:
A=A * ( I(A.n) &  T((-1,1,2)) )
A

$\left[ \begin{array}{cccc}3&-2&1&1\\0&1&1&1\\3&-1&3&4\\12&-16&1&2\\ \end{array} \right]$

##Ejercicio 4

4. Realiza el algoritmo de eliminación de Gauss-Jordan para la matriz del ejercicio 1, es decir continua las modificaciones de la matriz mediante operaciones elementales.
Por cada paso del algoritmo escribe la celda de código correspondiente.

Continuar a partir de aca:
$\left[ \begin{array}{cccc}3&0&0&0\\1&-1&0&0\\2&7&-33&0\\4&-4&15&162\\ \end{array} \right]$

In [71]:
M&T((fracc(1,3),1))

$\left[ \begin{array}{cccc}1&0&0&0\\\frac{1}{3}&-1&0&0\\\frac{2}{3}&7&-33&0\\\frac{4}{3}&-4&15&162\\ \end{array} \right]$

In [72]:
M&T((-1,2))

$\left[ \begin{array}{cccc}1&0&0&0\\\frac{1}{3}&1&0&0\\\frac{2}{3}&-7&-33&0\\\frac{4}{3}&4&15&162\\ \end{array} \right]$

In [73]:
M&T((-fracc(1,3),2,1))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\3&-7&-33&0\\0&4&15&162\\ \end{array} \right]$

In [74]:
M&T((-fracc(1,33),3))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\3&-7&1&0\\0&4&- \frac{5}{11}&162\\ \end{array} \right]$

In [75]:
M&T((7,3,2))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\3&0&1&0\\0&\frac{9}{11}&- \frac{5}{11}&162\\ \end{array} \right]$

In [76]:
M&T((-3,3,1))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&0&1&0\\\frac{15}{11}&\frac{9}{11}&- \frac{5}{11}&162\\ \end{array} \right]$

In [77]:
M&T((fracc(1,162),4))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&0&1&0\\\frac{15}{11}&\frac{9}{11}&- \frac{5}{11}&1\\ \end{array} \right]$

In [78]:
M&T((-fracc(15,11),4,1))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&0&1&0\\0&\frac{9}{11}&- \frac{5}{11}&1\\ \end{array} \right]$

In [79]:
M&T((-fracc(9,11),4,2))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&0&1&0\\0&0&- \frac{5}{11}&1\\ \end{array} \right]$

In [80]:
M&T((fracc(5,11),4,3))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&0&1&0\\0&0&0&1\\ \end{array} \right]$

##Ejercicio 5

5. Compara tus resultados del ejercicio 1 con el metodo Elim()

In [81]:
a=Vector((3,1,2,4)); b=Vector((-2,-1,1,-4)); c= Vector((2,-1,2,1)); d= Vector((1,-3,4,2))
metodo= Matrix([a,b,c,d])
metodo

$\left[ \begin{array}{cccc}3&-2&2&1\\1&-1&-1&-3\\2&1&2&4\\4&-4&1&2\\ \end{array} \right]$

In [82]:
Elim(metodo,1)

<IPython.core.display.Math object>

$\left[ \begin{array}{cccc}3&0&0&0\\1&-1&0&0\\2&7&-33&0\\4&-4&15&162\\ \end{array} \right]$

##Ejercicio 6

 6. Compara tus resultados del ejercicio 4 con el metodo ElimGJ()

In [83]:
a=Vector((3,1,2,4)); b=Vector((-2,-1,1,-4)); c= Vector((2,-1,2,1)); d= Vector((1,-3,4,2))
gauss= Matrix([a,b,c,d])
gauss

$\left[ \begin{array}{cccc}3&-2&2&1\\1&-1&-1&-3\\2&1&2&4\\4&-4&1&2\\ \end{array} \right]$

In [84]:
ElimGJ(N,1)

<IPython.core.display.Math object>

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&0&1&0\\0&0&0&1\\ \end{array} \right]$

##Ejercicio 7

7. Encuentra la inversa de la matriz del ejercicio 1.

In [85]:
inver= Matrix([a,b,c,d])
inver

$\left[ \begin{array}{cccc}3&-2&2&1\\1&-1&-1&-3\\2&1&2&4\\4&-4&1&2\\ \end{array} \right]$

In [86]:
C = inver.inversa()
C

$\left[ \begin{array}{cccc}- \frac{1}{6}&\frac{1}{2}&\frac{7}{18}&\frac{1}{18}\\- \frac{1}{9}&\frac{1}{3}&\frac{10}{27}&- \frac{5}{27}\\\frac{7}{9}&- \frac{1}{3}&- \frac{7}{27}&- \frac{10}{27}\\- \frac{5}{18}&- \frac{1}{6}&\frac{5}{54}&\frac{11}{54}\\ \end{array} \right]$

##Ejercicio 8

8. Resuelva el siguiente sistema de ecuaciones:

$$ \begin{array}{ccc}5x&+7y&-z&=6\\2x&+10y&-2z&=4\\x&+y&+z&=0\\ \end{array} $$

In [47]:
SistemaE = Matrix([[5,7,-1,6],[2,10,-2,4],[1,1,1,0]])
SistemaE

$\left[ \begin{array}{cccc}5&7&-1&6\\2&10&-2&4\\1&1&1&0\\ \end{array} \right]$

In [48]:
T((fracc(-1,2),2))&SistemaE
T((1,2,3))&SistemaE
T((fracc(-1,5),2))&SistemaE
T((4,2,3))&SistemaE

$\left[ \begin{array}{cccc}5&7&-1&6\\\frac{1}{5}&1&- \frac{1}{5}&\frac{2}{5}\\\frac{4}{5}&0&\frac{6}{5}&- \frac{2}{5}\\ \end{array} \right]$

In [49]:
T((fracc(1,5),1))&SistemaE
T((fracc(5,6),3))&SistemaE

$\left[ \begin{array}{cccc}1&\frac{7}{5}&- \frac{1}{5}&\frac{6}{5}\\\frac{1}{5}&1&- \frac{1}{5}&\frac{2}{5}\\\frac{2}{3}&0&1&- \frac{1}{3}\\ \end{array} \right]$

In [50]:
T((fracc(1,5),3,2))&SistemaE
T((fracc(-1,3),1,2))&SistemaE
T((fracc(-2,3),1,3))&SistemaE

$\left[ \begin{array}{cccc}1&\frac{7}{5}&- \frac{1}{5}&\frac{6}{5}\\0&\frac{8}{15}&\frac{1}{15}&- \frac{1}{15}\\0&- \frac{14}{15}&\frac{17}{15}&- \frac{17}{15}\\ \end{array} \right]$

In [51]:
T((fracc(15,8),2))&SistemaE
T((fracc(-7,5),2,1))&SistemaE
T((fracc(14,15),2,3))&SistemaE

$\left[ \begin{array}{cccc}1&0&- \frac{3}{8}&\frac{11}{8}\\0&1&\frac{1}{8}&- \frac{1}{8}\\0&0&\frac{5}{4}&- \frac{5}{4}\\ \end{array} \right]$

In [52]:
T((fracc(4,5),3))&SistemaE
T((fracc(-1,8),3,2))&SistemaE
T((fracc(3,8),3,1))&SistemaE

$\left[ \begin{array}{cccc}1&0&0&1\\0&1&0&0\\0&0&1&-1\\ \end{array} \right]$

La solucion al sistema de ecuaciones es el siguiente
$$x=1$$

$$y=0$$

$$z-1$$
